server:
  port: 8080
spring:
  redis:
    host: 172.30.66.104
    port: 6379
    # 密码 没有则可以不填
    password: 19e.com.cn
    # 如果使用的jedis 则将lettuce改成jedis即可
    database: 0
    jedis:
      pool:
        # 最大活跃链接数 默认8
        max-active: 5
        # 最大空闲连接数 默认8
        max-idle: 10
        # 最小空闲连接数 默认0
        min-idle: 0

